"""anadir masa muscular y detalle de medidas a registro peso

Revision ID: 0115d9e3a29c
Revises: 437bbcd587f7
Create Date: 2026-07-28 21:30:03.154636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0115d9e3a29c'
down_revision: Union[str, Sequence[str], None] = '437bbcd587f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_peso', sa.Column('masa_muscular_kg', sa.Float(), nullable=True))
    op.add_column('registros_peso', sa.Column('detalle_medidas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_peso', 'detalle_medidas')
    op.drop_column('registros_peso', 'masa_muscular_kg')
    # ### end Alembic commands ###
