"""anadir rol a usuario

Revision ID: 0ab3601d70bc
Revises: f050a2073c8d
Create Date: 2026-07-29 16:26:30.342915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab3601d70bc'
down_revision: Union[str, Sequence[str], None] = 'f050a2073c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Se añade con un valor temporal ('usuario') para las filas ya existentes,
    # y se quita el server_default justo después para que los inserts nuevos
    # exijan siempre un valor explícito (el modelo ya define default="usuario"
    # en Python).
    op.add_column(
        'usuarios',
        sa.Column('rol', sa.String(length=20), nullable=False, server_default='usuario'),
    )
    op.alter_column('usuarios', 'rol', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###
