"""anadir password_hash a usuario

Revision ID: 437bbcd587f7
Revises: 5b33464af2ec
Create Date: 2026-07-28 15:05:31.773432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437bbcd587f7'
down_revision: Union[str, Sequence[str], None] = '5b33464af2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Se añade con un valor temporal para las filas ya existentes (creadas antes de
    # que existiera login) — quedan con un hash imposible de verificar, es decir,
    # inutilizables para iniciar sesión hasta que se recree el usuario. Como es
    # solo un placeholder de migración, se quita el server_default justo después
    # para que los inserts nuevos exijan siempre un password_hash real.
    op.add_column(
        'usuarios',
        sa.Column('password_hash', sa.String(length=255), nullable=False, server_default=''),
    )
    op.alter_column('usuarios', 'password_hash', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
