"""crear tablas iniciales

Revision ID: 5aab47cf68b6
Revises: 
Create Date: 2026-07-23 17:34:51.422644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aab47cf68b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

GRUPOS_MUSCULARES = [
    "pecho",
    "espalda",
    "hombro",
    "bíceps",
    "tríceps",
    "antebrazo",
    "abdomen",
    "cuádriceps",
    "isquiotibiales",
    "glúteo",
    "gemelo",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_musculares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.Column('objetivo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ejercicios_grupos_musculares',
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('grupo_muscular_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['grupo_muscular_id'], ['grupos_musculares.id'], ),
    sa.PrimaryKeyConstraint('ejercicio_id', 'grupo_muscular_id')
    )
    op.create_table('sesiones_entrenamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_entrenamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    grupos_musculares_table = sa.table(
        "grupos_musculares",
        sa.column("nombre", sa.String),
    )
    op.bulk_insert(
        grupos_musculares_table,
        [{"nombre": nombre} for nombre in GRUPOS_MUSCULARES],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM grupos_musculares")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    op.drop_table('sesiones_entrenamiento')
    op.drop_table('ejercicios_grupos_musculares')
    op.drop_table('usuarios')
    op.drop_table('grupos_musculares')
    op.drop_table('ejercicios')
    # ### end Alembic commands ###
