"""anadir completada a sesion entrenamiento

Revision ID: 7cbe1bd46589
Revises: 0115d9e3a29c
Create Date: 2026-07-29 00:33:53.470349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbe1bd46589'
down_revision: Union[str, Sequence[str], None] = '0115d9e3a29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Se añade con un valor temporal (False) para las filas ya existentes, y se
    # quita el server_default justo después para que los inserts nuevos exijan
    # siempre un valor explícito (el modelo ya define default=False en Python).
    op.add_column(
        'sesiones_entrenamiento',
        sa.Column('completada', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('sesiones_entrenamiento', 'completada', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sesiones_entrenamiento', 'completada')
    # ### end Alembic commands ###
