"""anadir comidas, planes de alimentacion y registros

Revision ID: a58eab4b4eae
Revises: f5f6b74704f4
Create Date: 2026-07-28 13:51:08.475619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58eab4b4eae'
down_revision: Union[str, Sequence[str], None] = 'f5f6b74704f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('calorias', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes_alimentacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('numero_dia', sa.Integer(), nullable=False),
    sa.Column('franja', sa.String(length=20), nullable=False),
    sa.Column('comida_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comida_id'], ['comidas.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_alimentacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_alimentacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('plan_dia_id', sa.Integer(), nullable=True),
    sa.Column('comida_id', sa.Integer(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('calorias', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comida_id'], ['comidas.id'], ),
    sa.ForeignKeyConstraint(['plan_dia_id'], ['plan_dias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_alimentacion')
    op.drop_table('plan_dias')
    op.drop_table('planes_alimentacion')
    op.drop_table('comidas')
    # ### end Alembic commands ###
