"""anadir hora_inicio y hora_fin a sesion entrenamiento

Revision ID: f050a2073c8d
Revises: f7cb35f05a17
Create Date: 2026-07-29 15:48:14.881023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f050a2073c8d'
down_revision: Union[str, Sequence[str], None] = 'f7cb35f05a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sesiones_entrenamiento', sa.Column('hora_inicio', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sesiones_entrenamiento', sa.Column('hora_fin', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sesiones_entrenamiento', 'hora_fin')
    op.drop_column('sesiones_entrenamiento', 'hora_inicio')
    # ### end Alembic commands ###
