"""anadir rutinas y rutina_ejercicios, sesion requiere rutina

Revision ID: f5f6b74704f4
Revises: 5aab47cf68b6
Create Date: 2026-07-28 12:33:49.729176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f6b74704f4'
down_revision: Union[str, Sequence[str], None] = '5aab47cf68b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutina_ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('series_objetivo', sa.Integer(), nullable=False),
    sa.Column('repeticiones_objetivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sesiones_entrenamiento', sa.Column('rutina_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'fk_sesiones_entrenamiento_rutina_id',
        'sesiones_entrenamiento',
        'rutinas',
        ['rutina_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_sesiones_entrenamiento_rutina_id', 'sesiones_entrenamiento', type_='foreignkey'
    )
    op.drop_column('sesiones_entrenamiento', 'rutina_id')
    op.drop_table('rutina_ejercicios')
    op.drop_table('rutinas')
    # ### end Alembic commands ###
