"""anadir rutinas programadas

Revision ID: f7cb35f05a17
Revises: 7cbe1bd46589
Create Date: 2026-07-29 13:46:40.793071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cb35f05a17'
down_revision: Union[str, Sequence[str], None] = '7cbe1bd46589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutinas_programadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'dia_semana', name='uq_rutina_programada_usuario_dia_semana')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rutinas_programadas')
    # ### end Alembic commands ###
